name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install JS dependencies
        run: pnpm install
      - name: Build Tailwind CSS
        run: pnpm build:css
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs>=1.6.0 mkdocs-minify-plugin mkdocs-redirects mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin
      - name: Build MkDocs site
        run: mkdocs build --config-file example/mkdocs.yml
      - name: Link check
        run: mkdocs build --config-file example/mkdocs.yml --strict
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
